### ISSUE TITLE
Improvement Documentation

### ISSUE THREAD

**Issue by diecoz** [structy/porganizer#5]
Just improve How-To in Readme.md for users

**Comment by diecoz** [comment]
@avelino new branchs are not allowed, I improve Readme.md for new users.

![Screen Shot 2019-04-28 at 15 41 56](https://user-images.githubusercontent.com/4664420/56868706-4a29a980-69cc-11e9-8aed-0bbce8554b2a.png)

**Comment by avelino** [comment]
You do not have access to this repository, need to fork, commit on your fork and then send PR
